version: 0.0
os: linux
files:
  - source: /app
    destination: /var/www/html/
permissions:
    - object: /
hooks:
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 60
      runas: root  
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 60
      runas: root